openapi: 3.0.2
info:
    title: Currency
    version: 1.0.0
paths:
    /currencies:
        summary: Path used to manage the list of currencies.
        description: >-
            The REST endpoint/path used to list and create zero or more `Currency` entities.  This path
            contains a `GET` and `POST` operation to perform the list and create tasks, respectively.
        get:
            tags:
                - /currencies
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Currency"
                    description: Successful response - returns an array of `Currency` entities.
            operationId: getCurrencies
            summary: List All Currencies
            description: Gets a list of all `Currency` entities.
        post:
            requestBody:
                description: A new `Currency` to be created.
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Currency"
                        examples:
                            New Currency JSON:
                                value:
                                    name: some text
                                    bid: 45.15
                                    ask: 1.96
                required: true
            tags:
                - /currencies
            responses:
                "201":
                    description: Successful response.
            security:
                - bearer: []
            operationId: createCurrency
            summary: Create a Currency
            description: Creates a new instance of a `Currency`.
    "/currencies/{currencyId}":
        summary: Path used to manage a single Currency.
        description: >-
            The REST endpoint/path used to get, update, and delete single instances of an `Currency`.  This
            path contains `GET`, `PUT`, and `DELETE` operations used to perform the get, update, and delete
            tasks, respectively.
        get:
            tags:
                - /currencies
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Currency"
                    description: Successful response - returns a single `Currency`.
            operationId: getCurrency
            summary: Get a Currency
            description: Gets the details of a single instance of a `Currency`.
        put:
            requestBody:
                description: Updated `Currency` information.
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Currency"
                required: true
            tags:
                - /currencies
            responses:
                "202":
                    description: Successful response.
            operationId: updateCurrency
            summary: Update a Currency
            description: Updates an existing `Currency`.
        delete:
            tags:
                - /currencies
            parameters:
                - name: currencyId
                  description: A unique identifier for a `Currency`.
                  schema:
                      type: string
                  in: path
                  required: true
            responses:
                "204":
                    description: Successful response.
                "401":
                    description: Unauthorized
            security:
                - bearer: []
            operationId: deleteCurrency
            summary: Delete a Currency
            description: Deletes an existing `Currency`.
        parameters:
            - name: currencyId
              description: A unique identifier for a `Currency`.
              schema:
                  type: string
              in: path
              required: true
    /users/login:
        summary: Path used to manage the list of sessions.
        description: >-
            The REST endpoint/path used to list and create zero or more `Session` entities.  This path
            contains a `GET` and `POST` operation to perform the list and create tasks, respectively.
        post:
            requestBody:
                description: A new `Session` to be created.
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Session"
                        examples:
                            session:
                                value:
                                    username: axel
                                    password: axel
                required: true
            tags:
                - /sessions
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Session"
                    description: Successful response.
            operationId: createSession
            summary: Create a Session
            description: Creates a new instance of a `Session`.
components:
    schemas:
        Currency:
            title: Root Type for Currency
            description: ""
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                name:
                    type: string
                bid:
                    format: double
                    type: number
                ask:
                    format: double
                    type: number
            example:
                id: 1
                name: EURUSD
                bid: 1.1854
                ask: 1.1954
        Session:
            title: Root Type for Session
            description: ""
            type: object
            properties:
                message:
                    type: string
                token:
                    type: string
                admin:
                    type: boolean
            example:
                message: success
                token: >-
                    eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjc0NTczODc2LCJleHAiOjE2NzUxNzg2NzZ9.YYwu26QW2_8uA4pqI7Sa3eZvKd9LbFLHRLjprR72bQ4
                admin: true
    securitySchemes:
        bearer:
            scheme: bearer
            type: http
tags:
    - name: /currencies
      description: ""
    - name: /sessions
      description: ""
